---
- hosts: localhost
  name: "Set up hosts"
  tasks:
    - set_fact: sds_hosts_obj="{{ sds_hosts  | default({}) }}"
    - add_host:
        name: "{{ item.ip }}"
        groups: sds
        ansible_ssh_user: "{{ item.user }}"
        ansible_ssh_pass: "{{ item.pass }}"
      with_items: "{{ sds_hosts_obj }}"

    - set_fact: sdc_hosts_obj="{{ sdc_hosts  | default({}) }}"
    - add_host:
        name: "{{ item.ip }}"
        groups: sdc
        ansible_ssh_user: "{{ item.user }}"
        ansible_ssh_pass: "{{ item.pass }}"
      with_items: "{{ sdc_hosts_obj }}"

    - set_fact: mdm_hosts_obj="{{ mdm_hosts  | default({}) }}"
    - add_host:
        name: "{{ item.ip }}"
        groups: mdm
        ansible_ssh_user: "{{ item.user }}"
        ansible_ssh_pass: "{{ item.pass }}"
        mdm_data_ip: "{{ item.data_ip }}"
      with_items: "{{ mdm_hosts_obj }}"

- hosts: all
  tasks:
  - set_fact: scaleio_mdm_primary_ip="{{ hostvars[groups['mdm'][0]]['mdm_data_ip'] }}"
  - set_fact: scaleio_mdm_primary_hostname="{{ hostvars[groups['mdm'][0]]['inventory_hostname'] }}"
  - set_fact: scaleio_mdm_secondary_ip="{{ hostvars[groups['mdm'][1]]['mdm_data_ip'] }}"
  - set_fact: scaleio_mdm_secondary_hostname="{{ hostvars[groups['mdm'][1]]['inventory_hostname'] }}"
  - set_fact: scaleio_mdm_tertiary_ip="{{ hostvars[groups['mdm'][2]]['mdm_data_ip'] }}"
    when: hostvars[groups['mdm'][2]] is defined
  - set_fact: scaleio_mdm_ips="{{ scaleio_mdm_secondary_ip }},{{scaleio_mdm_primary_ip}}"
    when: scaleio_mdm_tertiary_ip is not defined
  - set_fact: scaleio_mdm_ips="{{ scaleio_mdm_secondary_ip }},{{scaleio_mdm_primary_ip}},{{scaleio_mdm_tertiary_ip}}"
    when: scaleio_mdm_tertiary_ip is defined

- hosts: sdc
  name: "Unmount and remove ScaleIO SDC"
  tasks:
    - include: roles/scaleio-sdc/tasks/remove-sdc.yml
  tags: scaleio-sdc-remove

- hosts: sds
  name: "Remove ScaleIO SDS and query SDS"
  tasks:
    - include: roles/scaleio-sds/tasks/remove-sds.yml
  tags: scaleio-sds-remove
