# vim:ft=ansible:
---

- hosts: localhost
  name: "set up hosts"
  tags: always
  tasks:
    - add_host:
        name: "{{ sds_host }}"
        groups: sds
        when: sds_host is defined

    - add_host:
        name: "{{ mdm_host }}"
        groups: mdm
        when: mdm_host is defined

- hosts: all
  name: "set up facts"
  tags: always
  tasks:
    - set_fact: scaleio_mdm_primary_ip="{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_mdm_primary_hostname="{{ hostvars[groups['mdm'][0]]['inventory_hostname'] }}"
    - set_fact: scaleio_mdm_ips="{{scaleio_mdm_primary_ip}}"

- hosts: sds
  name: "Install and configure ScaleIO SDS"
  roles:
    - scaleio-sds
  tags: scaleio-sds

